# Use OpenJDK as the base image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY target/MovieTicketService.jar /app/MovieTicketService.jar

# Expose port
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "MovieTicketService.jar"]